### PR TITLE
Add Automated Documentation to Rakefile

### LINKED ISSUE #132: Add Automated Documentation to Rakefile
## Description
**Enable Automated Documentation**
The Annotate gem allows us to have automatic documentation of model-related files and specs whenever a new migration is run, but comes out-of-the-box with the option disabled. 

## Implementation of the Solution
**Add Task to Rakefile**
* Navigate to `~/HuntersKeepers/Rakefile`

Add line to file, as shown in the documentation:
Screen Shot 2020-06-01 at 11 02 51 AM

**References**
[Annotate Documentation](https://github.com/ctran/annotate_models)

### PR DESCRIPTION
**Pull request by jash-kothari**
## Description of Feature or Issue
closes #132 

## Under-the-Hood Changes
Added auto annotation tasks to Rakefile.

### CODE REVIEW

**Comment by ChaelCodes** [comment]
Hello @jash-kothari ! You've made the changes requested in the issue and followed the documentation in Annotate's README, but I'm not seeing annotations on new models.
I followed these steps:

1. Pulling down your branch (I do see `Annotate.load_tasks` in the Rakefile)
1. Starting docker using `docker-compose up`
1. Running `docker exec -it hunterskeepers_web_1 bundle exec rails generate scaffold sillymodel name:string`
1. Running ` docker exec -it hunterskeepers_web_1 bundle exec rake db:migrate`

At this point, I would expect to have a Sillymodel class with an annotation for name at the top, but I do not.

Would you mind trying the `rails g annotate:install` instead?

**Review by ChaelCodes — CHANGES_REQUESTED** [review]
Hello @jash-kothari ! You've made the changes requested in the issue and followed the documentation in Annotate's README, but I'm not seeing annotations on new models.
I followed these steps:

1. Pulling down your branch (I do see `Annotate.load_tasks` in the Rakefile)
1. Starting docker using `docker-compose up`
1. Running `docker exec -it hunterskeepers_web_1 bundle exec rails generate scaffold sillymodel name:string`
1. Running ` docker exec -it hunterskeepers_web_1 bundle exec rake db:migrate`

At this point, I would expect to have a Sillymodel class with an annotation for name at the top, but I do not.

Would you mind trying the `rails g annotate:install` instead?

**Comment by jash-kothari** [comment]
@ChaelCodes - Have made the changes. But it is failing for code climate block too long rule.

What would be your suggestion here.

**Comment by ChaelCodes** [comment]
Hey @jash-kothari , I can test + review this tonight after work, but for now, I've marked that block too long complaint as a 'Won't Fix'. It's silly to care about block length in a config file.

**Review by ChaelCodes — APPROVED** [review]
This works great! Thank you for your changes.

**Comment by jash-kothari** [comment]
Your welcome @ChaelCodes.

**Pull request merged**
